version: "3"
services:
  payment-service:
    build: .
    command: serve 
    ports:
      - 8080:8080
    environment:
      - PS_APP_STORE_REDISADDRESS=redis:6379
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - 6379:6379